### ISSUE TITLE
More information about your setup

### ISSUE THREAD

**Issue by traveling-developer** [Lyliya/homebridge-ledstrip-ble#1]
Hi @Lyliya thanks for that plugin. Exactly what I searched for.
Could you maybe give some more information how your setup looks like?
How did you connect the LED strip to the controller?
What LED strip are you using?
Is it working fine?

Thanks so much 😊

**Comment by Lyliya** [comment]
Hey @traveling-developer ! Quite a surprise that someone found this plugin aha, this was developed for thoses leds : https://www.amazon.fr/gp/product/B08HB33S37 that i got for 10€, they are based on this controller : https://www.aliexpress.com/item/4000208329326.html . 

I dont really know if we can tell which led are compatible with this plugin as i create it only for the led i have in my room. My guess is that led using the app "Lotus Lantern" for control should be compatible.

 - Could you maybe give some more information how your setup looks like?
 I use homebridge on a docker on debian and have a bluetooth adapter (https://www.amazon.fr/gp/product/B07NQ5YGDW) to make the connection between the PC and the led.

If you want to try the plugin, you'll need to connect the led based on this configuration in homebridge : https://github.com/Lyliya/homebridge-ledstrip-ble#configuration . You can find your uuid with a quick scan

- Is it working fine?
The plugin work really well with one ledstrip, i cant tell if it work with more, as i only use one. As im the only user for now, i cant tell you if there is possible bug with different hardware etc, but feel free to open an issue if you encountered some

**Comment by traveling-developer** [comment]
Thanks :)
