### ISSUE TITLE
Homebridge complains about plugin identifier

### ISSUE THREAD

**Issue by sebi-alt** [Lyliya/homebridge-ledstrip-ble#2]
When starting homebridge I get this message:
```
Loaded plugin: @lyliya/homebridge-ledstrip-ble@1.2.3
Plugin '@lyliya/homebridge-ledstrip-ble' tried to register with an incorrect plugin identifier: 'homebridge-ledstrip-ble'. Please report this to the developer!
Registering accessory '@lyliya/homebridge-ledstrip-ble.LedStrip'
```
I do not know if this is relevant or not, but decided to mention this here since the message advises to report this to the developer.

- node: v16.13.1
- Npm: v8.1.2
- homebridge: v1.4.0
- @lyliya/homebridge-ledstrip-ble: v1.2.3

Thank you for this plugin 👍

**Comment by Lyliya** [comment]
Hey @sebi-alt 
That's just a warning and the plugin should work as expected, it's a thing i tried to fix long time ago, but didn't find the way to do it x)
