### ISSUE TITLE
Raspberry Pi Problem

### ISSUE THREAD

**Issue by lucacasula91** [Lyliya/homebridge-ledstrip-ble#4]
I cannot change status On/Off, colors etc. on my Raspberry with Homebridge.

I've debugged in Device.js file and added extra console logs. Basically the bluetooth device is visible, i can also connect to it, but the await  on peripheral.discoverSomeServicesAndCharacteristicsAsync never return the service and the characteristics.

This means that 'this.write' is undefined and nothing works fine.

**Comment by lucacasula91** [comment]
All works fine with 1.0.15 version.

**Comment by bjclopes** [comment]
I've been having the exact same problem. I figured out that the wi-fi and bluetooth connection on the Raspberry Pi were interfering. The solution I found was to connect the Raspberry Pi to a 5GHz Wi-Fi only and the interference is gone.
